[package]
name = "expense_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.137"
